language: python
python:
  - "3.6"
install:
  - pip install -v .
  - pip install -r requirements.txt
  - pip install codecov
script:
  - coverage run --source hardware setup.py test
  - coverage report -m
  - codecov
after_success:
  - "cd docs && make html"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/_build/html
  on:
    branch: master
