language: python
python: 
  - "3.6"
script:
  - "sh ./tests/all_tests.sh"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/_build
  on:
    branch: master